language: node_js
node_js:
  - 8
os:
  - linux
after_success:
  - npm install now https://github.com/ebidel/lighthouse-ci.git --no-save
  - chmod ugo+x ./now-deploy.sh
  - ./now-deploy.sh
branches:
  only: 
    - gh-pages
