language: node_js
node_js:
  - 8
os:
  - linux
after_success:
  - npm install now https://github.com/ebidel/lighthouse-ci.git puppeteer --no-save
  - chmod ugo+x ./tools/now-deploy.sh ./tools/imgur.sh
  - ./tools/now-deploy.sh
branches:
  only: 
    - gh-pages
